STARTED JOB AT: Mon Jan 16 01:23:15 EST 2023

2023-01-16 01:23:19.246572 (reading meta data, all rows)
2023-01-16 01:29:43.466558 (done reading meta data, 238803125 rows)
2023-01-16 01:31:40.063897, on 0 - 20000000
2023-01-16 03:07:49.066517 (saving csv 0: 0 - 20000000)
2023-01-16 04:37:16.580082, on 20000000 - 40000000
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/threading.py", line 973, in _bootstrap_inner
    self.run()
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/threading.py", line 910, in run
    self._target(*self._args, **self._kwargs)
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/pool.py", line 513, in _handle_workers
    cls._maintain_pool(ctx, Process, processes, pool, inqueue,
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/pool.py", line 337, in _maintain_pool
    Pool._repopulate_pool_static(ctx, Process, processes, pool,
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/pool.py", line 326, in _repopulate_pool_static
    w.start()
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/popen_fork.py", line 66, in _launch
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory
Process ForkPoolWorker-115:
Traceback (most recent call last):
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/pool.py", line 131, in worker
    put((job, i, result))
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/queues.py", line 372, in put
    obj = _ForkingPickler.dumps(obj)
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
MemoryError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/n/sw/eb/apps/centos7/Anaconda3/2022.05/lib/python3.9/multiprocessing/pool.py", line 134, in worker
    util.debug("Possible encoding error while sending result: %s" % (
MemoryError
slurmstepd: error: *** JOB 39193631 ON holy7c26501 CANCELLED AT 2023-01-16T12:09:38 ***
